theme: jekyll-theme-cayman
header_pages:
 - index.md
 - io2presentation.md
 - io3projectspecification.md
 - io4finalreport.md



 # Staticman
staticman:
 allowedFields: ['address', 'name', 'title', 'description', 'rating']
 branch: gh-pages
 commitMessage: "Hey human, here is a new entry."
 filename: "entry{@timestamp}"
 format: yml
 moderation: true
 path: "_data/reviews"
 requiredFields: ['name', 'title', 'description', 'rating']